---
all:
  children:
    root_servers:
      hosts:
        staging-root:
          ansible_host: "5.78.113.169"
          ansible_user: root
          ansible_ssh_private_key_file: "~/.ssh/plo-scope-staging"
          ansible_python_interpreter: /usr/bin/python3
          ansible_become: yes
          ansible_become_method: sudo
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          environment: staging
          domain: "staging.ploscope.com"
          project_dir: "/root/plo-solver"
          ssl_dir: "/root/ssl"
        production-root:
          ansible_host: "CHANGE_ME"
          ansible_user: root
          ansible_ssh_private_key_file: "~/.ssh/plo-scope-production"
          ansible_python_interpreter: /usr/bin/python3
          ansible_become: yes
          ansible_become_method: sudo
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          environment: production
          domain: "ploscope.com"
          project_dir: "/root/plo-solver"
          ssl_dir: "/root/ssl"

    appuser_servers:
      hosts:
        staging-appuser:
          ansible_host: "5.78.113.169"
          ansible_user: appuser
          ansible_ssh_private_key_file: "~/.ssh/plo-scope-staging"
          ansible_python_interpreter: /usr/bin/python3
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: "{{ appuser_password }}"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          environment: staging
          domain: "staging.ploscope.com"
          project_dir: "/home/appuser/plo-solver"
          ssl_dir: "/home/appuser/ssl" 
        production-appuser:
          ansible_host: "CHANGE_ME"
          ansible_user: appuser
          ansible_ssh_private_key_file: "~/.ssh/plo-scope-production"
          ansible_python_interpreter: /usr/bin/python3
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: "{{ appuser_password }}"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          environment: production
          domain: "ploscope.com"
          project_dir: "/home/appuser/plo-solver"
          ssl_dir: "/home/appuser/ssl" 
