---
- name: Update apt package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes

- name: Create appuser
  user:
    name: appuser
    shell: /bin/bash
    create_home: yes
    state: present

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add appuser to docker group
  user:
    name: appuser
    groups: docker
    append: yes

- name: Ensure appuser is in sudo group
  user:
    name: appuser
    groups: sudo
    state: present
    append: yes