---
services:
  db-migrate:
    image: ploscope/db-init:${DB_INIT_TAG:-staging}
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: production
        BUILDKIT_INLINE_CACHE: 1
    container_name: db-migrate-${ENVIRONMENT}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_MIGRATE_HOST=${POSTGRES_MIGRATE_HOST}
      - SCHEMA_USER=${POSTGRES_USER}
      - SCHEMA_PASSWORD=${SCHEMA_PASSWORD}
      - POSTGRES_SCHEMA_USER=${POSTGRES_SCHEMA_USER}
      - POSTGRES_SCHEMA_PASSWORD=${POSTGRES_SCHEMA_PASSWORD}
      - LOG_LEVEL=INFO
      - BUILD_ENV=production
      - RESTART_POLICY=always
      - VOLUME_MODE=rwd
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: "no"
    networks:
      plo-network-cloud:
        ipv4_address: 172.30.1.26

  db:
    image: postgres:15
    container_name: db-${ENVIRONMENT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - LOG_LEVEL=INFO

    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_DATA_PATH:-./data/postgres}:/var/lib/postgresql/data
      - ${POSTGRES_BACKUP_PATH:-./backups}:/backups:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      plo-network-cloud:
        ipv4_address: 172.30.1.14

networks:
  plo-network-cloud:
    external: true
