---
- name: Create SSL directory
  file:
    path: "{{ ssl_dir }}"
    state: directory
    mode: '0755'
    owner: appuser
    group: appuser
- name: Create SSL certificate file placeholder
  file:
    path: "{{ ssl_dir }}/cert.pem"
    state: touch
    mode: '0644'
- name: Create SSL private key file placeholder
  file:
    path: "{{ ssl_dir }}/privkey.pem"
    state: touch
    mode: '0600'